insert into ISO_COUNTRY values(1,'AF','Afghanistan');
insert into ISO_COUNTRY values(2,'AX','Aland Islands');
insert into ISO_COUNTRY values(3,'AL','Albania');
insert into ISO_COUNTRY values(4,'DZ','Algeria');
insert into ISO_COUNTRY values(5,'AS','American Samoa');
insert into ISO_COUNTRY values(6,'AD','Andorra');
insert into ISO_COUNTRY values(7,'AO','Angola');
insert into ISO_COUNTRY values(8,'AI','Anguilla');
insert into ISO_COUNTRY values(9,'AQ','Antarctica');
insert into ISO_COUNTRY values(10,'AG','Antigua and Barbuda');
insert into ISO_COUNTRY values(11,'AR','Argentina');
insert into ISO_COUNTRY values(12,'AM','Armenia');
insert into ISO_COUNTRY values(13,'AW','Aruba');
insert into ISO_COUNTRY values(14,'AU','Australia');
insert into ISO_COUNTRY values(15,'AT','Austria');
insert into ISO_COUNTRY values(16,'AZ','Azerbaijan');
insert into ISO_COUNTRY values(17,'BH','Bahrain');
insert into ISO_COUNTRY values(18,'BS','Bahamas');
insert into ISO_COUNTRY values(19,'BD','Bangladesh');
insert into ISO_COUNTRY values(20,'BB','Barbados');
insert into ISO_COUNTRY values(21,'BY','Belarus');
insert into ISO_COUNTRY values(22,'BE','Belgium');
insert into ISO_COUNTRY values(23,'BZ','Belize');
insert into ISO_COUNTRY values(24,'BJ','Benin');
insert into ISO_COUNTRY values(25,'BM','Bermuda');
insert into ISO_COUNTRY values(26,'BT','Bhutan');
insert into ISO_COUNTRY values(27,'BO','Bolivia, Plurinational State of');
insert into ISO_COUNTRY values(28,'BQ','Bonaire, Sint Eustatius and Saba');
insert into ISO_COUNTRY values(29,'BA','Bosnia and Herzegovina');
insert into ISO_COUNTRY values(30,'BW','Botswana');
insert into ISO_COUNTRY values(31,'BV','Bouvet Island');
insert into ISO_COUNTRY values(32,'BR','Brazil');
insert into ISO_COUNTRY values(33,'IO','British Indian Ocean Territory');
insert into ISO_COUNTRY values(34,'BN','Brunei Darussalam');
insert into ISO_COUNTRY values(35,'BG','Bulgaria');
insert into ISO_COUNTRY values(36,'BF','Burkina Faso');
insert into ISO_COUNTRY values(37,'BI','Burundi');
insert into ISO_COUNTRY values(38,'KH','Cambodia');
insert into ISO_COUNTRY values(39,'CM','Cameroon');
insert into ISO_COUNTRY values(40,'CA','Canada');
insert into ISO_COUNTRY values(41,'CV','Cape Verde');
insert into ISO_COUNTRY values(42,'KY','Cayman Islands');
insert into ISO_COUNTRY values(43,'CF','Central African Republic');
insert into ISO_COUNTRY values(44,'TD','Chad');
insert into ISO_COUNTRY values(45,'CL','Chile');
insert into ISO_COUNTRY values(46,'CN','China');
insert into ISO_COUNTRY values(47,'CX','Christmas Island');
insert into ISO_COUNTRY values(48,'CC','Cocos (Keeling) Islands');
insert into ISO_COUNTRY values(49,'CO','Colombia');
insert into ISO_COUNTRY values(50,'KM','Comoros');
insert into ISO_COUNTRY values(51,'CG','Congo');
insert into ISO_COUNTRY values(52,'CD','Congo, the Democratic Republic of the');
insert into ISO_COUNTRY values(53,'CK','Cook Islands');
insert into ISO_COUNTRY values(54,'CR','Costa Rica');
insert into ISO_COUNTRY values(56,'HR','Croatia');
insert into ISO_COUNTRY values(57,'CU','Cuba');
insert into ISO_COUNTRY values(58,'CW','Curaçao');
insert into ISO_COUNTRY values(59,'CY','Cyprus');
insert into ISO_COUNTRY values(60,'CZ','Czech Republic');
insert into ISO_COUNTRY values(61,'DK','Denmark');
insert into ISO_COUNTRY values(62,'DJ','Djibouti');
insert into ISO_COUNTRY values(63,'DM','Dominica');
insert into ISO_COUNTRY values(64,'DO','Dominican Republic');
insert into ISO_COUNTRY values(65,'EC','Ecuador');
insert into ISO_COUNTRY values(66,'EG','Egypt');
insert into ISO_COUNTRY values(67,'SV','El Salvador');
insert into ISO_COUNTRY values(68,'GQ','Equatorial Guinea');
insert into ISO_COUNTRY values(69,'ER','Eritrea');
insert into ISO_COUNTRY values(70,'EE','Estonia');
insert into ISO_COUNTRY values(71,'ET','Ethiopia');
insert into ISO_COUNTRY values(72,'FK','Falkland Islands (Malvinas)');
insert into ISO_COUNTRY values(73,'FO','Faroe Islands');
insert into ISO_COUNTRY values(74,'FJ','Fiji');
insert into ISO_COUNTRY values(75,'FI','Finland');
insert into ISO_COUNTRY values(76,'FR','France');
insert into ISO_COUNTRY values(77,'GF','French Guiana');
insert into ISO_COUNTRY values(78,'PF','French Polynesia');
insert into ISO_COUNTRY values(79,'TF','French Southern Territories');
insert into ISO_COUNTRY values(80,'GA','Gabon');
insert into ISO_COUNTRY values(81,'GM','Gambia');
insert into ISO_COUNTRY values(82,'GE','Georgia');
insert into ISO_COUNTRY values(83,'DE','Germany');
insert into ISO_COUNTRY values(84,'GH','Ghana');
insert into ISO_COUNTRY values(85,'GI','Gibraltar');
insert into ISO_COUNTRY values(86,'GR','Greece');
insert into ISO_COUNTRY values(87,'GL','Greenland');
insert into ISO_COUNTRY values(88,'GD','Grenada');
insert into ISO_COUNTRY values(89,'GP','Guadeloupe');
insert into ISO_COUNTRY values(90,'GU','Guam');
insert into ISO_COUNTRY values(91,'GT','Guatemala');
insert into ISO_COUNTRY values(92,'GG','Guernsey');
insert into ISO_COUNTRY values(93,'GN','Guinea');
insert into ISO_COUNTRY values(94,'GW','Guinea-Bissau');
insert into ISO_COUNTRY values(95,'GY','Guyana');
insert into ISO_COUNTRY values(96,'HT','Haiti');
insert into ISO_COUNTRY values(97,'HM','Heard Island and McDonald Islands');
insert into ISO_COUNTRY values(98,'VA','Holy See (Vatican City State)');
insert into ISO_COUNTRY values(99,'HN','Honduras');
insert into ISO_COUNTRY values(100,'HK','Hong Kong');
insert into ISO_COUNTRY values(101,'HU','Hungary');
insert into ISO_COUNTRY values(102,'IS','Iceland');
insert into ISO_COUNTRY values(103,'IN','India');
insert into ISO_COUNTRY values(104,'ID','Indonesia');
insert into ISO_COUNTRY values(105,'IR','Iran, Islamic Republic of');
insert into ISO_COUNTRY values(106,'IQ','Iraq');
insert into ISO_COUNTRY values(107,'IE','Ireland');
insert into ISO_COUNTRY values(108,'IM','Isle of Man');
insert into ISO_COUNTRY values(109,'IL','Israel');
insert into ISO_COUNTRY values(110,'IT','Italy');
insert into ISO_COUNTRY values(111,'JM','Jamaica');
insert into ISO_COUNTRY values(112,'JP','Japan');
insert into ISO_COUNTRY values(113,'JE','Jersey');
insert into ISO_COUNTRY values(114,'JO','Jordan');
insert into ISO_COUNTRY values(115,'KZ','Kazakhstan');
insert into ISO_COUNTRY values(116,'KE','Kenya');
insert into ISO_COUNTRY values(117,'KI','Kiribati');
insert into ISO_COUNTRY values(119,'KR','Korea, Republic of');
insert into ISO_COUNTRY values(120,'KW','Kuwait');
insert into ISO_COUNTRY values(121,'KG','Kyrgyzstan');
insert into ISO_COUNTRY values(123,'LV','Latvia');
insert into ISO_COUNTRY values(124,'LB','Lebanon');
insert into ISO_COUNTRY values(125,'LS','Lesotho');
insert into ISO_COUNTRY values(126,'LR','Liberia');
insert into ISO_COUNTRY values(127,'LY','Libya');
insert into ISO_COUNTRY values(128,'LI','Liechtenstein');
insert into ISO_COUNTRY values(129,'LT','Lithuania');
insert into ISO_COUNTRY values(130,'LU','Luxembourg');
insert into ISO_COUNTRY values(131,'MO','Macao');
insert into ISO_COUNTRY values(132,'MK','Macedonia, the Former Yugoslav Republic of');
insert into ISO_COUNTRY values(133,'MG','Madagascar');
insert into ISO_COUNTRY values(134,'MW','Malawi');
insert into ISO_COUNTRY values(135,'MY','Malaysia');
insert into ISO_COUNTRY values(136,'MV','Maldives');
insert into ISO_COUNTRY values(137,'ML','Mali');
insert into ISO_COUNTRY values(138,'MT','Malta');
insert into ISO_COUNTRY values(139,'MH','Marshall Islands');
insert into ISO_COUNTRY values(140,'MQ','Martinique');
insert into ISO_COUNTRY values(141,'MR','Mauritania');
insert into ISO_COUNTRY values(142,'MU','Mauritius');
insert into ISO_COUNTRY values(143,'YT','Mayotte');
insert into ISO_COUNTRY values(144,'MX','Mexico');
insert into ISO_COUNTRY values(145,'FM','Micronesia, Federated States of');
insert into ISO_COUNTRY values(146,'MD','Moldova, Republic of');
insert into ISO_COUNTRY values(147,'MC','Monaco');
insert into ISO_COUNTRY values(148,'MN','Mongolia');
insert into ISO_COUNTRY values(149,'ME','Montenegro');
insert into ISO_COUNTRY values(150,'MS','Montserrat');
insert into ISO_COUNTRY values(151,'MA','Morocco');
insert into ISO_COUNTRY values(152,'MZ','Mozambique');
insert into ISO_COUNTRY values(153,'MM','Myanmar');
insert into ISO_COUNTRY values(154,'NA','Namibia');
insert into ISO_COUNTRY values(155,'NR','Nauru');
insert into ISO_COUNTRY values(156,'NP','Nepal');
insert into ISO_COUNTRY values(157,'NL','Netherlands');
insert into ISO_COUNTRY values(158,'NC','New Caledonia');
insert into ISO_COUNTRY values(159,'NZ','New Zealand');
insert into ISO_COUNTRY values(160,'NI','Nicaragua');
insert into ISO_COUNTRY values(161,'NE','Niger');
insert into ISO_COUNTRY values(162,'NG','Nigeria');
insert into ISO_COUNTRY values(163,'NU','Niue');
insert into ISO_COUNTRY values(164,'NF','Norfolk Island');
insert into ISO_COUNTRY values(165,'MP','Northern Mariana Islands');
insert into ISO_COUNTRY values(166,'NO','Norway');
insert into ISO_COUNTRY values(167,'OM','Oman');
insert into ISO_COUNTRY values(168,'PK','Pakistan');
insert into ISO_COUNTRY values(169,'PW','Palau');
insert into ISO_COUNTRY values(170,'PS','Palestine, State of');
insert into ISO_COUNTRY values(171,'PA','Panama');
insert into ISO_COUNTRY values(172,'PG','Papua New Guinea');
insert into ISO_COUNTRY values(173,'PY','Paraguay');
insert into ISO_COUNTRY values(174,'PE','Peru');
insert into ISO_COUNTRY values(175,'PH','Philippines');
insert into ISO_COUNTRY values(176,'PN','Pitcairn');
insert into ISO_COUNTRY values(177,'PL','Poland');
insert into ISO_COUNTRY values(178,'PT','Portugal');
insert into ISO_COUNTRY values(179,'PR','Puerto Rico');
insert into ISO_COUNTRY values(180,'QA','Qatar');
insert into ISO_COUNTRY values(181,'RE','Réunion');
insert into ISO_COUNTRY values(182,'RO','Romania');
insert into ISO_COUNTRY values(183,'RU','Russian Federation');
insert into ISO_COUNTRY values(184,'RW','Rwanda');
insert into ISO_COUNTRY values(185,'BL','Saint Barthélemy');
insert into ISO_COUNTRY values(186,'SH','Saint Helena, Ascension and Tristan da Cunha');
insert into ISO_COUNTRY values(187,'KN','Saint Kitts and Nevis');
insert into ISO_COUNTRY values(188,'LC','Saint Lucia');
insert into ISO_COUNTRY values(189,'MF','Saint Martin (French part)');
insert into ISO_COUNTRY values(190,'PM','Saint Pierre and Miquelon');
insert into ISO_COUNTRY values(191,'VC','Saint Vincent and the Grenadines');
insert into ISO_COUNTRY values(192,'WS','Samoa');
insert into ISO_COUNTRY values(193,'SM','San Marino');
insert into ISO_COUNTRY values(194,'ST','Sao Tome and Principe');
insert into ISO_COUNTRY values(195,'SA','Saudi Arabia');
insert into ISO_COUNTRY values(196,'SN','Senegal');
insert into ISO_COUNTRY values(197,'RS','Serbia');
insert into ISO_COUNTRY values(198,'SC','Seychelles');
insert into ISO_COUNTRY values(199,'SL','Sierra Leone');
insert into ISO_COUNTRY values(200,'SG','Singapore');
insert into ISO_COUNTRY values(201,'SX','Sint Maarten (Dutch part)');
insert into ISO_COUNTRY values(202,'SK','Slovakia');
insert into ISO_COUNTRY values(203,'SI','Slovenia');
insert into ISO_COUNTRY values(204,'SB','Solomon Islands');
insert into ISO_COUNTRY values(205,'SO','Somalia');
insert into ISO_COUNTRY values(206,'ZA','South Africa');
insert into ISO_COUNTRY values(207,'GS','South Georgia and the South Sandwich Islands');
insert into ISO_COUNTRY values(208,'SS','South Sudan');
insert into ISO_COUNTRY values(209,'ES','Spain');
insert into ISO_COUNTRY values(210,'LK','Sri Lanka');
insert into ISO_COUNTRY values(211,'SD','Sudan');
insert into ISO_COUNTRY values(212,'SR','Suriname');
insert into ISO_COUNTRY values(213,'SJ','Svalbard and Jan Mayen');
insert into ISO_COUNTRY values(214,'SZ','Swaziland');
insert into ISO_COUNTRY values(215,'SE','Sweden');
insert into ISO_COUNTRY values(216,'CH','Switzerland');
insert into ISO_COUNTRY values(217,'SY','Syrian Arab Republic');
insert into ISO_COUNTRY values(218,'TW','Taiwan, Province of China');
insert into ISO_COUNTRY values(219,'TJ','Tajikistan');
insert into ISO_COUNTRY values(220,'TZ','Tanzania, United Republic of');
insert into ISO_COUNTRY values(221,'TH','Thailand');
insert into ISO_COUNTRY values(222,'TL','Timor-Leste');
insert into ISO_COUNTRY values(223,'TG','Togo');
insert into ISO_COUNTRY values(224,'TK','Tokelau');
insert into ISO_COUNTRY values(225,'TO','Tonga');
insert into ISO_COUNTRY values(226,'TT','Trinidad and Tobago');
insert into ISO_COUNTRY values(227,'TN','Tunisia');
insert into ISO_COUNTRY values(228,'TR','Turkey');
insert into ISO_COUNTRY values(229,'TM','Turkmenistan');
insert into ISO_COUNTRY values(230,'TC','Turks and Caicos Islands');
insert into ISO_COUNTRY values(231,'TV','Tuvalu');
insert into ISO_COUNTRY values(232,'UG','Uganda');
insert into ISO_COUNTRY values(233,'UA','Ukraine');
insert into ISO_COUNTRY values(234,'AE','United Arab Emirates');
insert into ISO_COUNTRY values(235,'GB','United Kingdom');
insert into ISO_COUNTRY values(236,'US','United States');
insert into ISO_COUNTRY values(237,'UM','United States Minor Outlying Islands');
insert into ISO_COUNTRY values(238,'UY','Uruguay');
insert into ISO_COUNTRY values(239,'UZ','Uzbekistan');
insert into ISO_COUNTRY values(240,'VU','Vanuatu');
insert into ISO_COUNTRY values(241,'VE','Venezuela, Bolivarian Republic of');
insert into ISO_COUNTRY values(242,'VN','Viet Nam');
insert into ISO_COUNTRY values(243,'VG','Virgin Islands, British');
insert into ISO_COUNTRY values(244,'VI','Virgin Islands, U.S.');
insert into ISO_COUNTRY values(245,'WF','Wallis and Futuna');
insert into ISO_COUNTRY values(246,'EH','Western Sahara');
insert into ISO_COUNTRY values(247,'YE','Yemen');
insert into ISO_COUNTRY values(248,'ZM','Zambia');
insert into ISO_COUNTRY values(249,'ZW','Zimbabwe');


INSERT INTO  COUNTRY_ENTITY  values ('US', '1', 'USD', 'America', 'Y', 5, 1 );
INSERT INTO  COUNTRY_ENTITY  values ('AD', '1', 'ADM', 'Andora', 'Y', 5, 1 );